{
 "title": "Pravega Operation Dashboard",
 "tags": [ "pravega" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY=\"host\""
   }
  ]
 },
 "panels": [
  { "title": "Current Latency Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segment Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_segment_write_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_segment_write_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_storage_write_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_storage_write_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_bookkeeper_write_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_bookkeeper_write_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Total Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_bookkeeper_total_write_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_bookkeeper_total_write_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_segment_read_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_segment_read_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_storage_read_latency_ms_percentile",
     "query": "SELECT max(\"host_value\") FROM (SELECT  last(\"value\") AS \"host_value\" FROM \"two_hour\".\"pravega_segmentstore_storage_read_latency_ms_percentile\" WHERE (\"phi\" = '0.99' AND \"host\" =~ /.*$host.*/) AND $timeFilter GROUP BY \"host\") ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Segment Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "global($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_bytes_global",
     "query": "SELECT mean(\"value\")  / 10 FROM \"pravega_segmentstore_segment_write_bytes_global\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "sum(segment_write_bytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "sum(global)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_bytes_global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Segment Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "global($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes_global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "sum(segment_read_bytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "sum(global)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes_global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "global($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes_global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "global($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes_global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SLTS Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SLTS Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_read_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_read_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Concat Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_concat_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_concat_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Segmentstore - Segment Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Segment Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Create Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_create_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Delete Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_delete_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segmentstore - Storage Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Create Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_create_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Delete Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_delete_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Concat Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_concat_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Truncate Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_truncate_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Read Index Scan Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_slts_read_index_scan_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Metadata Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_metadata_commit_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Metadata Get Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_metadata_get_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Metadata Table Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_metadata_table_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "SLTS Metadata Table Get Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_metadata_table_get_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segmentstore - Container Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "Container Processors In Flight Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_processor_in_flight_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Queue Size Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_queue_size_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Batch Size  Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_process_operations_batch_size_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Commit Count Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_commit_memory_count_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Processor Delay Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_throttler",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "throttler" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_processor_delay_ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Queue Wait Time Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_queue_wait_time_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_commit_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Commit Memory Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_commit_memory_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Segmentstore - Bookkeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "BK Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Ledger Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "c$tag_container",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_ledger_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Queue Size Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_queue_size_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Queue Fill Rate Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_queue_fill_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Exclusive Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Total Write Latency (including Queue)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_total_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  }
 ]
}