{
 "title": "Pravega Stream Dashboard v0.7",
 "tags": [
  "pravega",
  "imported"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "scope",
    "query": "SHOW TAG VALUES WITH KEY = \"scope\""
   },
   {
    "name": "streams",
    "label": "stream type",
    "query": "SHOW TAG VALUES WITH KEY = \"kind\""
   },
   {
    "name": "pattern",
    "query": "SHOW TAG VALUES WITH KEY = \"pattern\" WHERE \"kind\" =~ /$streams/"
   },
   {
    "name": "stream",
    "query": "SHOW TAG VALUES WITH KEY = \"stream\" WHERE \"scope\" =~ /^$scope$/"
   },
   {
    "name": "retention",
    "query": "SHOW RETENTION POLICIES ON pravega"
   }
  ]
 },
 "panels": [
  {
   "title": "Segment Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_controller_segments_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "binBps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "binBps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_read_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Tx opened",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_opened",
     "select": [
      [
       { "params": [ "Gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$stream segments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pravega_controller_segments_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "$stream splits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "splits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_segment_splits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "$stream merges",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "merges",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_segment_merges",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  { "title": "Write Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total write bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "write_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Max segment write bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "max(write_rate)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_segment_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "stream", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  { "title": "Read Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total read bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "read_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_read_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  {
   "title": "Max segment read bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "max(read_rate)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_segment_read_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "stream", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  { "title": "Write Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total write events/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "alias": "event_rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_write_events",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  {
   "title": "Max segment write events/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "alias": "max(event_rate)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_segment_write_events",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "stream", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Transactions Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "created",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_created",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_committed",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    },
    {
     "alias": "aborted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_aborted",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Gauges",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "opened",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_opened",
     "select": [
      [
       { "params": [ "Gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    },
    {
     "alias": "timedout",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_transactions_timedout",
     "select": [
      [
       { "params": [ "Gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" },
      { "condition": "AND", "key": "stream", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  }
 ]
}