#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Initialize variables
  hosts: all
  connection: ssh
  tasks:
    - set_fact:
        private_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        zookeeperServers: "{{ groups['zookeeper'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"

- name: Restart brokers with new configurations
  hosts: pulsar
  become: true
  tasks:
    - set_fact:
        max_heap_memory: "{{ pulsar_max_heap_memory | default('16g') }}"
        max_direct_memory: "{{ pulsar_max_direct_memory | default('48g') }}"
    - systemd:
        state: stopped
        name: pulsar
    - name: Set up pulsar.service
      template:
        src: templates/pulsar.service
        dest: /etc/systemd/system/pulsar.service
    - name: Set up pulsar_env.sh
      template:
        src: templates/pulsar_env.sh
        dest: /opt/pulsar/conf/pulsar_env.sh
    - name: Set up broker.conf
      template:
        src: templates/broker.conf
        dest: /opt/pulsar/conf/broker.conf
    - name: Set up configurations of protocol handlers
      template:
        src: "templates/{{ item.conf }}"
        dest: "/opt/pulsar/conf/{{ item.conf }}"
      loop: "{{ protocol_handlers }}"
      when: protocol_handlers is defined
    - set_fact:
        protocols: "{{ protocols | default([]) + [ item.protocol ] }}"
      loop: "{{ protocol_handlers }}"
      when: protocol_handlers is defined
    - name: Enable protocol handlers
      lineinfile:
        path: /opt/pulsar/conf/broker.conf
        line: "messagingProtocols={{ protocols | join(',') }}"
    - name: Read configurations of all protocol handlers
      shell: |
        grep -v "^#" "{{ '/opt/pulsar/conf/' + item.conf }}"
      loop: "{{ protocol_handlers }}"
      when: protocol_handlers is defined
      register: conf_files
    - name: Read configurations of all protocol handlers
      shell: |
        grep -v "^#" "{{ '/opt/pulsar/conf/' + item.conf }}"
      loop: "{{ protocol_handlers }}"
      when: protocol_handlers is defined
      register: conf_files
    - name: Update broker.conf for protocol handlers
      lineinfile:
        path: /opt/pulsar/conf/broker.conf
        line: "{{ item.stdout_lines | join('\n') }}"
      loop: "{{ conf_files.results }}"
      when: conf_files is defined
    - systemd:
        state: started
        daemon_reload: yes
        name: pulsar
